services:
  db:
    image: pgvector/pgvector:pg16
    container_name: travel_exp_planner_rfl_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travel_exp_planner_rfl_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
