/**
 * Maps questionnaire option labels → emoji.
 * Ported from frontend/n7_legacy_streamlit_ui/views/input/questionnaire_data.py (EMOJI_MAP).
 */
export const EMOJI_MAP: Record<string, string> = {
  // Q1 — categories
  "Núi cao": "🏔️",
  "Đồi núi": "⛰️",
  "Thung lũng": "🌄",
  "Cao nguyên": "🏜️",
  "Bãi biển": "🏖️",
  Đảo: "🏝️",
  Sông: "🛶",
  Hồ: "🦢",
  "Vườn quốc gia": "🌲",
  "Rừng rậm": "🌳",
  "Khu bảo tồn": "🌿",
  "Rạn san hô": "🪸",
  "Thành thị": "🏙️",
  "Phố cổ": "🏛️",
  "Làng quê": "🏘️",
  // Q1 — specifics
  "Đá vôi & Karst": "🪨",
  "Hang động": "🦇",
  "Đồi cát": "🏜️",
  "Quần đảo": "🏝️",
  "Thác nước": "💦",
  "Suối nước nóng": "♨️",
  "Đồng bằng": "🏞️",
  "Rừng ngập mặn": "🌱",
  "Khu dự trữ sinh quyển": "🐒",
  "Săn mây": "☁️",
  "Mùa lúa chín": "🌾",
  "Mùa hoa nở": "🌸",

  // Q2
  "Một mình": "👤",
  "Cặp đôi": "💑",
  "Gia đình": "👨‍👩‍👧",
  "Nhóm bạn": "🎉",
  "Đồng nghiệp": "🏢",

  // Q3
  "Lãng mạn": "💕",
  "Hoang dã": "🐾",
  "Hoài cổ": "🎞️",
  "Tâm linh": "📿",
  "Yên bình": "🧘",
  Chill: "🥤",
  "Chậm rãi": "🐚",
  "Ấm cúng": "🕯️",
  "Sôi động": "⚡",
  "Phiêu lưu": "🌋",
  "Góc khuất ẩn mình": "🕵️",
  "Văn hóa địa phương": "🇻🇳",
  "Nên thơ": "🖼️",
  Bohemian: "🎸",
  "Mộc mạc": "🪵",
  "Hiện đại": "🏙️",

  // Q4
  "Vỉa hè": "🍜",
  "Đặc sản": "🍲",
  "Nhà hàng": "🍴",
  "Tour ẩm thực": "🍢",
  "Hải sản": "🦐",
  "Ẩm thực cung đình": "👑",
  "Hữu cơ & Sạch": "🌿",
  "Ăn chay (vegetarian)": "🥗",
  "Thuần chay (vegan)": "🥑",
  Halal: "☪️",
  "Cà phê Việt Nam": "☕",
  "Bia hơi": "🍻",
  "Bia thủ công": "🍺",
  "Hoa quả nhiệt đới": "🍍",
  "Rượu truyền thống": "🍶",
  "Trà cao nguyên": "🍵",

  // Q5
  Trekking: "🥾",
  "Leo núi": "👟",
  "Tour xe máy": "🏍️",
  "Phượt xe máy / Loop": "🛵",
  "Đạp xe": "🚴",
  "Chạy trail": "🏃",
  "Leo vách đá": "🧗",
  "Thám hiểm hang động": "🔦",
  Canyoning: "🧗",
  "Cắm trại": "⛺",
  "Tour xe Jeep": "🚙",
  "Tour xe địa hình": "🏎️",
  "Lặn có bình khí": "🤿",
  "Lặn ống thở": "🐠",
  "Chèo thuyền kayak": "🛶",
  "SUP (đứng chèo)": "🏄",
  "Lướt sóng": "🏄",
  Kitesurfing: "🪁",
  "Chèo thuyền vượt thác": "🌊",
  "Nhảy thác": "🪨",
  "Bơi lội": "🏊",
  "Tắm bùn khoáng": "🧖",
  "Du thuyền qua đêm": "🛳️",
  "Thuyền gỗ truyền thống": "⛵",
  "Ngồi đò qua hang động": "🛶",
  "Chèo bè tre": "🎋",
  "Thuyền thúng": "🧺",
  "Tàu cao tốc": "🚤",
  "Du thuyền sông": "🛥️",
  "Câu cá": "🎣",
  "Câu mực ban đêm": "🦑",
  "Cáp treo": "🚡",
  "Dù lượn": "🪂",
  "Khinh khí cầu": "🎈",
  "Hành trình tàu hỏa": "🚂",
  "Tàu hoả đêm": "🛌",
  "Tour xích lô": "🚲",
  "Chụp ảnh phong cảnh": "📷",
  "Mua sắm": "🛍️",
  Golf: "⛳",
  "Công viên giải trí": "🎡",
  "Công viên nước": "⛲",
  "Dã ngoại / Picnic": "🧺",
  "Tour đêm": "🌙",
  "Spa & Massage": "💆",
  "Tắm thảo dược": "🛁",
  "Retreat Yoga": "🧘",
  "Retreat sức khoẻ": "🌿",
  "Tắm suối nước nóng": "♨️",
  "Lớp học nấu ăn": "👨‍🍳",
  "Lớp làm gốm": "🏺",
  "Làm đèn lồng": "🏮",
  "Thăm trang trại": "🧑‍🌾",
  "Thưởng trà": "🍵",
  "Tour cà phê": "☕",
  "Biểu diễn nghệ thuật": "🎭",
  "Múa rối nước": "🎎",
  "Âm nhạc truyền thống": "🎶",
  "Làng nghề thủ công": "🔨",
  "Hoạt động thiện nguyện": "🤝",

  // Q6
  "Đi về trong ngày": "☀️",
  "Cuối tuần": "🧳",
  "Dài ngày": "📅",
  Workcation: "💻",
  "Phượt bụi": "🎒",
  "Tuần trăng mật": "💍",
  "Kỷ niệm": "🥂",
  "Team building": "🤝",
  "Tiết kiệm / Bụi": "🫰",
  "Tầm trung": "💵",
  "Sang trọng": "💎",
  "Chậm & Sâu": "🐚",
  "Khu nghỉ dưỡng": "🏰",
  "Khách sạn boutique": "🛎️",
  Homestay: "🏡",
  "Eco lodge": "🛖",
  Glamping: "🏕️",
  "Làng chài": "🛶",
  "Chợ nổi": "🚣",
  "Chợ đêm": "🏮",
  "Phố đi bộ": "🚶",
  "Bar rooftop": "🍸",
  "Du lịch sinh thái": "🍃",
  "Du lịch nông nghiệp": "🧑‍🌾",
  "Du lịch sức khoẻ": "🧘",
  "Tour ẩm thực chuyên đề": "🍳",
  "Du lịch chiến trường": "🎖️",
  "Du lịch tâm linh": "🛕",
  "Du lịch thể thao": "🏃",
  "Tour chụp ảnh": "🔭",
  "Du lịch y tế": "🏥",
  "Digital nomad": "🌍",
  "MICE & Doanh nghiệp": "💼",
};

export const FALLBACK_EMOJI = "✨";

export function emojiFor(label: string): string {
  return EMOJI_MAP[label] ?? FALLBACK_EMOJI;
}
