from typing import Dict, List, Any


# ===========================================================================
# LOCATION_PROFILES: Đặc trưng từng địa điểm
# Dùng bởi n5_activity_generator._get_profile()
# Keys bắt buộc: tags, description, best_season, indoor_ratio, price_range, region
# ===========================================================================
LOCATION_PROFILES: Dict[str, Any] = {
    "Sa Pa": {
        "tags": ["mountain", "trekking", "nature", "cool_weather", "photography", "culture", "ethnic", "scenic", "rice_terrace"],
        "description": "Thị trấn vùng cao Sa Pa với ruộng bậc thang hùng vĩ và văn hóa dân tộc phong phú",
        "best_season": ["sep", "oct", "nov", "mar", "apr"],
        "indoor_ratio": 0.2,
        "price_range": (50_000, 800_000),
        "region": "northwest",
    },
    "Phú Quốc": {
        "tags": ["beach", "sea", "resort", "relax", "island", "diving", "seafood", "snorkeling"],
        "description": "Đảo ngọc Phú Quốc với bãi biển trong xanh và hải sản tươi ngon",
        "best_season": ["nov", "dec", "jan", "feb", "mar", "apr"],
        "indoor_ratio": 0.15,
        "price_range": (50_000, 1_200_000),
        "region": "south",
    },
    "Đà Lạt": {
        "tags": ["mountain", "cool_weather", "flower", "nature", "romantic", "photography", "trekking", "scenic"],
        "description": "Thành phố ngàn hoa Đà Lạt với khí hậu mát mẻ và cảnh quan thơ mộng",
        "best_season": ["dec", "jan", "feb", "mar", "nov"],
        "indoor_ratio": 0.25,
        "price_range": (50_000, 600_000),
        "region": "central_highlands",
    },
    "Hội An": {
        "tags": ["culture", "history", "food", "photography", "heritage", "relax", "beach", "architecture"],
        "description": "Phố cổ Hội An với kiến trúc đặc sắc và ẩm thực phong phú",
        "best_season": ["feb", "mar", "apr", "may"],
        "indoor_ratio": 0.35,
        "price_range": (50_000, 1_000_000),
        "region": "central",
    },
    "Hạ Long": {
        "tags": ["sea", "nature", "cruise", "adventure", "island", "cave", "kayak", "scenic"],
        "description": "Vịnh Hạ Long với ngàn hòn đảo đá vôi và những hang động kỳ bí",
        "best_season": ["mar", "apr", "may", "sep", "oct", "nov"],
        "indoor_ratio": 0.1,
        "price_range": (100_000, 1_500_000),
        "region": "northeast",
    },
    "Hà Giang": {
        "tags": ["mountain", "nature", "adventure", "culture", "motorbiking", "scenic", "ethnic", "trekking", "canyon", "rice_terrace"],
        "description": "Cao nguyên đá Hà Giang hoang sơ với đèo Mã Pí Lèng hùng vĩ",
        "best_season": ["sep", "oct", "nov", "mar", "apr"],
        "indoor_ratio": 0.15,
        "price_range": (30_000, 500_000),
        "region": "northeast",
    },
    "Nha Trang": {
        "tags": ["beach", "sea", "entertainment", "relax", "diving", "seafood", "island", "snorkeling"],
        "description": "Thành phố biển Nha Trang với bãi biển xanh và các khu vui chơi sầm uất",
        "best_season": ["jan", "feb", "mar", "apr", "jun", "jul", "aug"],
        "indoor_ratio": 0.2,
        "price_range": (50_000, 1_000_000),
        "region": "central",
    },
    "Huế": {
        "tags": ["culture", "history", "food", "architecture", "heritage", "relax", "scenic"],
        "description": "Cố đô Huế với hệ thống lăng tẩm, đền đài và ẩm thực cung đình tinh tế",
        "best_season": ["feb", "mar", "apr", "may"],
        "indoor_ratio": 0.30,
        "price_range": (30_000, 500_000),
        "region": "central",
    },
    "Đà Nẵng": {
        "tags": ["beach", "sea", "culture", "food", "urban", "relax", "photography", "scenic"],
        "description": "Thành phố đáng sống Đà Nẵng với bãi biển Mỹ Khê và cầu Rồng nổi tiếng",
        "best_season": ["feb", "mar", "apr", "may", "jun", "jul", "aug"],
        "indoor_ratio": 0.25,
        "price_range": (50_000, 800_000),
        "region": "central",
    },
    "Phong Nha": {
        "tags": ["cave", "nature", "adventure", "trekking", "river", "jungle", "scenic"],
        "description": "Vườn quốc gia Phong Nha - Kẻ Bàng với hệ thống hang động lớn nhất thế giới",
        "best_season": ["feb", "mar", "apr", "may", "jun", "jul", "aug"],
        "indoor_ratio": 0.05,
        "price_range": (50_000, 800_000),
        "region": "central",
    },
}


# ===========================================================================
# SIGHTSEEING_BOOST_TAGS: Tags nào tăng điểm sightseeing_priority cho template
# Dùng bởi n5_activity_generator._score_templates_for_location()
# ===========================================================================
SIGHTSEEING_BOOST_TAGS: Dict[str, float] = {
    "mountain":    0.20,
    "nature":      0.15,
    "waterfall":   0.20,
    "scenic":      0.15,
    "photography": 0.10,
    "beach":       0.10,
    "sea":         0.10,
    "island":      0.10,
    "trekking":    0.10,
    "cave":        0.15,
    "rice_terrace": 0.20,
    "canyon":      0.20,
    "cool_weather": 0.05,
    "flower":      0.10,
    "river":       0.10,
    "jungle":      0.10,
    "forest":      0.10,
    "landscape":   0.15,
    "motorbiking": 0.05,
    "cruise":      0.10,
}


# ===========================================================================
# VARIATION_MODIFIERS: Tạo biến thể activities để đạt đủ 100/location
# Dùng bởi n5_activity_generator._expand_templates()
# Keys bắt buộc: suffix, desc_prefix, intensity_delta, time_of_day_suitable
# ===========================================================================
VARIATION_MODIFIERS: List[Dict[str, Any]] = [
    {
        "suffix": "buổi sáng sớm",
        "desc_prefix": "Bắt đầu ngày mới tuyệt vời: ",
        "intensity_delta": 0.05,
        "time_of_day_suitable": "morning",
    },
    {
        "suffix": "cùng bạn bè",
        "desc_prefix": "Cùng bạn bè tận hưởng: ",
        "intensity_delta": 0.10,
        "time_of_day_suitable": None,
    },
    {
        "suffix": "hoàng hôn",
        "desc_prefix": "Tận hưởng buổi chiều tà với: ",
        "intensity_delta": -0.05,
        "time_of_day_suitable": "afternoon",
    },
    {
        "suffix": "phiên bản VIP",
        "desc_prefix": "Trải nghiệm đẳng cấp cao cấp: ",
        "intensity_delta": 0.0,
        "time_of_day_suitable": None,
    },
    {
        "suffix": "cho người mới",
        "desc_prefix": "Hoàn toàn phù hợp cho người mới: ",
        "intensity_delta": -0.20,
        "time_of_day_suitable": None,
    },
    {
        "suffix": "cùng gia đình",
        "desc_prefix": "Trải nghiệm ý nghĩa bên gia đình: ",
        "intensity_delta": -0.10,
        "time_of_day_suitable": None,
    },
    {
        "suffix": "ban đêm",
        "desc_prefix": "Khám phá vẻ đẹp huyền ảo về đêm: ",
        "intensity_delta": 0.0,
        "time_of_day_suitable": "night",
    },
    {
        "suffix": "hidden gem",
        "desc_prefix": "Bí mật chỉ dành riêng cho bạn: ",
        "intensity_delta": 0.05,
        "time_of_day_suitable": None,
    },
    {
        "suffix": "có hướng dẫn viên",
        "desc_prefix": "Khám phá chuyên sâu cùng hướng dẫn viên địa phương: ",
        "intensity_delta": 0.0,
        "time_of_day_suitable": None,
    },
    {
        "suffix": "thư giãn",
        "desc_prefix": "Phiên bản nhẹ nhàng, thư thái: ",
        "intensity_delta": -0.15,
        "time_of_day_suitable": None,
    },
    {
        "suffix": "mạo hiểm",
        "desc_prefix": "Thử thách bản thân với phiên bản mạo hiểm: ",
        "intensity_delta": 0.20,
        "time_of_day_suitable": None,
    },
    {
        "suffix": "solo",
        "desc_prefix": "Tự do khám phá theo cách của riêng bạn: ",
        "intensity_delta": 0.0,
        "time_of_day_suitable": None,
    },
]


# ===========================================================================
# ACTIVITY_TYPE_BANK: Template bank theo loại hoạt động
# Dùng bởi n5_activity_generator._expand_templates()
#
# Mỗi template cần đủ các keys:
#   name_template, description_template, activity_type, activity_subtype,
#   compatible_location_tags, intensity_range, physical_level_range,
#   social_level_range, duration_range, price_level_range [1.0-5.0],
#   indoor_outdoor, weather_dependent, time_of_day_suitable, sightseeing_priority
# ===========================================================================
ACTIVITY_TYPE_BANK: Dict[str, List[Dict[str, Any]]] = {

    # ── NATURE (sightseeing_priority cao: 0.75-0.95) ──────────────────────
    "nature": [
        {
            "name_template": "Trekking ngắm cảnh tại {location}",
            "description_template": "Khám phá vẻ đẹp thiên nhiên hoang sơ tại {location} qua những cung đường trekking tuyệt đẹp. Hít thở không khí trong lành và chiêm ngưỡng phong cảnh hùng vĩ trải dài trước mắt.",
            "activity_type": "nature",
            "activity_subtype": "nature_walk",
            "compatible_location_tags": ["mountain", "nature", "trekking", "jungle", "forest", "scenic"],
            "intensity_range": [0.5, 0.8],
            "physical_level_range": [0.5, 0.8],
            "social_level_range": [0.3, 0.7],
            "duration_range": [120, 240],
            "price_level_range": [1.0, 2.5],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.85,
        },
        {
            "name_template": "Ngắm bình minh tại {location}",
            "description_template": "Thức dậy sớm để chiêm ngưỡng khoảnh khắc bình minh kỳ diệu tại {location}. Ánh nắng đầu ngày chiếu rọi trên núi đồi tạo nên cảnh tượng không thể quên.",
            "activity_type": "nature",
            "activity_subtype": "sunrise_viewing",
            "compatible_location_tags": ["mountain", "nature", "photography", "scenic", "beach", "sea", "cool_weather"],
            "intensity_range": [0.1, 0.3],
            "physical_level_range": [0.1, 0.3],
            "social_level_range": [0.2, 0.5],
            "duration_range": [60, 120],
            "price_level_range": [1.0, 1.5],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.95,
        },
        {
            "name_template": "Ngắm hoàng hôn tại {location}",
            "description_template": "Tận hưởng khoảnh khắc hoàng hôn tuyệt đẹp tại {location} khi mặt trời từ từ lặn xuống chân trời. Bầu trời nhuốm sắc cam hồng tạo nên bức tranh thiên nhiên sống động.",
            "activity_type": "nature",
            "activity_subtype": "sunset_viewing",
            "compatible_location_tags": ["mountain", "nature", "photography", "scenic", "beach", "sea", "island", "cool_weather"],
            "intensity_range": [0.1, 0.3],
            "physical_level_range": [0.1, 0.2],
            "social_level_range": [0.3, 0.6],
            "duration_range": [60, 120],
            "price_level_range": [1.0, 1.5],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "afternoon",
            "sightseeing_priority": 0.95,
        },
        {
            "name_template": "Chụp ảnh phong cảnh {location}",
            "description_template": "Khám phá những góc chụp đẹp nhất tại {location} cùng camera. Từ ruộng bậc thang, thác nước đến bãi biển — mỗi khoảnh khắc là một tác phẩm nghệ thuật.",
            "activity_type": "nature",
            "activity_subtype": "landscape_photography",
            "compatible_location_tags": ["nature", "photography", "mountain", "scenic", "beach", "flower", "rice_terrace", "cool_weather"],
            "intensity_range": [0.2, 0.5],
            "physical_level_range": [0.2, 0.5],
            "social_level_range": [0.2, 0.5],
            "duration_range": [90, 180],
            "price_level_range": [1.0, 2.0],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.90,
        },
        {
            "name_template": "Khám phá hang động tại {location}",
            "description_template": "Bước vào thế giới kỳ ảo của những hang động tự nhiên tại {location}. Những nhũ đá, măng đá triệu năm tuổi tạo nên cảnh quan choáng ngợp dưới lòng đất.",
            "activity_type": "nature",
            "activity_subtype": "viewpoint",
            "compatible_location_tags": ["cave", "nature", "adventure", "trekking", "river"],
            "intensity_range": [0.3, 0.6],
            "physical_level_range": [0.3, 0.6],
            "social_level_range": [0.3, 0.6],
            "duration_range": [60, 180],
            "price_level_range": [1.5, 3.0],
            "indoor_outdoor": "mixed",
            "weather_dependent": False,
            "time_of_day_suitable": "anytime",
            "sightseeing_priority": 0.85,
        },
        {
            "name_template": "Ngắm cảnh panorama {location}",
            "description_template": "Leo lên điểm nhìn panorama để chiêm ngưỡng toàn cảnh {location} trải rộng bao la. Tầm mắt không giới hạn ôm trọn núi đồi, sông suối và bầu trời xanh thẳm.",
            "activity_type": "nature",
            "activity_subtype": "panorama_viewpoint",
            "compatible_location_tags": ["mountain", "scenic", "photography", "trekking", "nature", "canyon"],
            "intensity_range": [0.3, 0.6],
            "physical_level_range": [0.3, 0.6],
            "social_level_range": [0.2, 0.5],
            "duration_range": [90, 180],
            "price_level_range": [1.0, 2.5],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.95,
        },
        {
            "name_template": "Đi thuyền ngắm cảnh {location}",
            "description_template": "Thong thả trôi trên mặt nước ngắm nhìn cảnh quan tuyệt vời của {location} từ góc độ hoàn toàn khác. Gió mát và khung cảnh hùng vĩ hai bên bờ mang lại cảm giác bình yên.",
            "activity_type": "nature",
            "activity_subtype": "boat_sightseeing",
            "compatible_location_tags": ["sea", "river", "island", "cave", "kayak", "cruise", "scenic"],
            "intensity_range": [0.1, 0.3],
            "physical_level_range": [0.1, 0.3],
            "social_level_range": [0.3, 0.7],
            "duration_range": [90, 240],
            "price_level_range": [2.0, 4.0],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.90,
        },
        {
            "name_template": "Khám phá thiên nhiên hoang dã {location}",
            "description_template": "Hòa mình vào thiên nhiên nguyên sơ tại {location}, quan sát động thực vật bản địa trong môi trường tự nhiên. Trải nghiệm eco-tour thân thiện với môi trường.",
            "activity_type": "nature",
            "activity_subtype": "eco_tour",
            "compatible_location_tags": ["nature", "jungle", "forest", "trekking", "mountain", "river"],
            "intensity_range": [0.3, 0.6],
            "physical_level_range": [0.3, 0.6],
            "social_level_range": [0.3, 0.6],
            "duration_range": [120, 300],
            "price_level_range": [1.5, 3.0],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.80,
        },
        {
            "name_template": "Ngắm ruộng bậc thang {location}",
            "description_template": "Chiêm ngưỡng những thửa ruộng bậc thang xếp tầng kỳ vĩ tại {location} — kiệt tác nghệ thuật của người nông dân vùng cao. Màu sắc thay đổi theo mùa tạo nên vẻ đẹp độc đáo.",
            "activity_type": "nature",
            "activity_subtype": "scenic_walk",
            "compatible_location_tags": ["rice_terrace", "mountain", "nature", "photography", "scenic", "ethnic"],
            "intensity_range": [0.2, 0.5],
            "physical_level_range": [0.2, 0.5],
            "social_level_range": [0.2, 0.5],
            "duration_range": [90, 180],
            "price_level_range": [1.0, 2.0],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.92,
        },
        {
            "name_template": "Ngắm cảnh từ đỉnh núi {location}",
            "description_template": "Chinh phục độ cao để đứng trên đỉnh núi {location} nhìn xuống toàn bộ thung lũng bên dưới. Cảm giác tự do và hùng vĩ chỉ có được khi đứng trên đỉnh cao.",
            "activity_type": "nature",
            "activity_subtype": "nature_photography",
            "compatible_location_tags": ["mountain", "scenic", "trekking", "nature", "canyon", "cool_weather"],
            "intensity_range": [0.4, 0.7],
            "physical_level_range": [0.4, 0.7],
            "social_level_range": [0.2, 0.5],
            "duration_range": [180, 360],
            "price_level_range": [1.0, 2.5],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.90,
        },
    ],

    # ── ADVENTURE (sightseeing_priority thấp: 0.25-0.45) ──────────────────
    "adventure": [
        {
            "name_template": "Leo núi chinh phục đỉnh cao {location}",
            "description_template": "Thử thách bản thân với cung đường leo núi mạo hiểm tại {location}. Chinh phục đỉnh cao và cảm nhận niềm vui chiến thắng khi đứng trên đỉnh hùng vĩ.",
            "activity_type": "adventure",
            "activity_subtype": "hiking",
            "compatible_location_tags": ["mountain", "trekking", "adventure", "nature", "cool_weather"],
            "intensity_range": [0.7, 1.0],
            "physical_level_range": [0.7, 1.0],
            "social_level_range": [0.3, 0.7],
            "duration_range": [240, 480],
            "price_level_range": [2.0, 4.0],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.40,
        },
        {
            "name_template": "Chèo kayak khám phá {location}",
            "description_template": "Trải nghiệm cảm giác mạnh khi chèo kayak trên mặt nước tại {location}. Khám phá những ngóc ngách ẩn mình và tận hưởng cảm giác tự do trên sóng nước.",
            "activity_type": "adventure",
            "activity_subtype": "kayaking",
            "compatible_location_tags": ["sea", "river", "kayak", "island", "cave", "adventure"],
            "intensity_range": [0.5, 0.8],
            "physical_level_range": [0.5, 0.8],
            "social_level_range": [0.3, 0.7],
            "duration_range": [90, 180],
            "price_level_range": [2.0, 3.5],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.30,
        },
        {
            "name_template": "Lặn biển ngắm san hô tại {location}",
            "description_template": "Khám phá thế giới dưới nước đầy màu sắc tại {location}. Lặn ngắm san hô và đàn cá nhiều màu sắc trong làn nước trong xanh tuyệt đẹp.",
            "activity_type": "adventure",
            "activity_subtype": "snorkeling",
            "compatible_location_tags": ["sea", "beach", "diving", "island", "snorkeling"],
            "intensity_range": [0.4, 0.7],
            "physical_level_range": [0.4, 0.7],
            "social_level_range": [0.4, 0.7],
            "duration_range": [120, 240],
            "price_level_range": [2.5, 4.0],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.25,
        },
        {
            "name_template": "Đi xe máy khám phá {location}",
            "description_template": "Tự do khám phá {location} trên yên xe máy qua những cung đường uốn lượn hùng vĩ. Cảm nhận gió mát và tự tạo hành trình theo ý muốn của mình.",
            "activity_type": "adventure",
            "activity_subtype": "motorbiking",
            "compatible_location_tags": ["mountain", "motorbiking", "adventure", "scenic", "trekking", "canyon"],
            "intensity_range": [0.4, 0.7],
            "physical_level_range": [0.3, 0.6],
            "social_level_range": [0.2, 0.5],
            "duration_range": [180, 360],
            "price_level_range": [1.5, 3.0],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.40,
        },
        {
            "name_template": "Cắm trại dưới sao {location}",
            "description_template": "Trải nghiệm đêm nằm ngủ dưới bầu trời đầy sao tại {location}. Nướng BBQ, hát hò bên lửa trại và ngắm Milky Way trong đêm yên tĩnh.",
            "activity_type": "adventure",
            "activity_subtype": "camping",
            "compatible_location_tags": ["mountain", "nature", "adventure", "trekking", "jungle", "scenic"],
            "intensity_range": [0.3, 0.6],
            "physical_level_range": [0.3, 0.6],
            "social_level_range": [0.5, 0.9],
            "duration_range": [360, 480],
            "price_level_range": [2.0, 3.5],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "night",
            "sightseeing_priority": 0.35,
        },
        {
            "name_template": "Thám hiểm hang động {location}",
            "description_template": "Phiêu lưu vào lòng hang động bí ẩn tại {location}. Vượt qua những thách thức địa hình và khám phá vẻ đẹp ẩn sâu trong lòng đất.",
            "activity_type": "adventure",
            "activity_subtype": "cave_exploration",
            "compatible_location_tags": ["cave", "adventure", "nature", "trekking", "river"],
            "intensity_range": [0.5, 0.8],
            "physical_level_range": [0.5, 0.8],
            "social_level_range": [0.3, 0.6],
            "duration_range": [120, 300],
            "price_level_range": [2.5, 4.0],
            "indoor_outdoor": "mixed",
            "weather_dependent": False,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.30,
        },
        {
            "name_template": "Tắm thác nước tại {location}",
            "description_template": "Tìm đến những thác nước hoang sơ tại {location} để tắm mát và thư giãn. Tiếng nước chảy rì rào và màu xanh trong vắt của nước tạo cảm giác sảng khoái.",
            "activity_type": "adventure",
            "activity_subtype": "waterfall_visit",
            "compatible_location_tags": ["waterfall", "nature", "mountain", "trekking", "jungle", "adventure"],
            "intensity_range": [0.4, 0.7],
            "physical_level_range": [0.4, 0.7],
            "social_level_range": [0.4, 0.7],
            "duration_range": [120, 240],
            "price_level_range": [1.0, 2.5],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.45,
        },
    ],

    # ── RELAXATION (sightseeing_priority trung bình: 0.10-0.60) ───────────
    "relaxation": [
        {
            "name_template": "Thư giãn tắm biển tại {location}",
            "description_template": "Tắm mình trong làn nước biển mát lành tại {location}. Nằm dài trên bãi cát trắng mịn, nghe sóng vỗ và tận hưởng cảm giác bình yên tuyệt đối.",
            "activity_type": "relaxation",
            "activity_subtype": "beach_relaxation",
            "compatible_location_tags": ["beach", "sea", "relax", "island", "resort"],
            "intensity_range": [0.0, 0.2],
            "physical_level_range": [0.0, 0.2],
            "social_level_range": [0.2, 0.6],
            "duration_range": [120, 300],
            "price_level_range": [1.0, 2.0],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.50,
        },
        {
            "name_template": "Trải nghiệm spa và massage tại {location}",
            "description_template": "Thả lỏng cơ thể với dịch vụ spa cao cấp tại {location}. Được xoa bóp bằng tinh dầu thảo mộc địa phương và tận hưởng cảm giác thư thái từ đầu đến chân.",
            "activity_type": "relaxation",
            "activity_subtype": "spa_massage",
            "compatible_location_tags": ["resort", "relax", "health", "beach", "sea", "cool_weather"],
            "intensity_range": [0.0, 0.1],
            "physical_level_range": [0.0, 0.1],
            "social_level_range": [0.1, 0.4],
            "duration_range": [60, 120],
            "price_level_range": [2.5, 4.5],
            "indoor_outdoor": "indoor",
            "weather_dependent": False,
            "time_of_day_suitable": "afternoon",
            "sightseeing_priority": 0.10,
        },
        {
            "name_template": "Cà phê ngắm cảnh {location}",
            "description_template": "Ngồi thư giãn tại quán cà phê view đẹp nhất {location}, nhâm nhi ly cà phê thơm ngon trong khi chiêm ngưỡng cảnh quan tuyệt vời xung quanh.",
            "activity_type": "relaxation",
            "activity_subtype": "scenic_walk",
            "compatible_location_tags": ["nature", "mountain", "scenic", "photography", "relax", "cool_weather", "beach", "culture"],
            "intensity_range": [0.0, 0.15],
            "physical_level_range": [0.0, 0.15],
            "social_level_range": [0.2, 0.6],
            "duration_range": [60, 120],
            "price_level_range": [1.0, 2.5],
            "indoor_outdoor": "mixed",
            "weather_dependent": False,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.60,
        },
        {
            "name_template": "Yoga và thiền định tại {location}",
            "description_template": "Bắt đầu ngày mới với buổi tập yoga và thiền định trong không gian thiên nhiên bình yên của {location}. Cân bằng tâm thân giữa không khí trong lành.",
            "activity_type": "relaxation",
            "activity_subtype": "nature_walk",
            "compatible_location_tags": ["nature", "mountain", "resort", "relax", "health", "beach", "cool_weather"],
            "intensity_range": [0.1, 0.3],
            "physical_level_range": [0.1, 0.3],
            "social_level_range": [0.1, 0.4],
            "duration_range": [60, 90],
            "price_level_range": [1.5, 3.0],
            "indoor_outdoor": "outdoor",
            "weather_dependent": True,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.45,
        },
        {
            "name_template": "Dạo bộ buổi tối tại {location}",
            "description_template": "Thư thái dạo bộ qua những con phố đêm lung linh của {location}. Ngắm nhìn cuộc sống về đêm và tận hưởng bầu không khí dễ chịu sau hoàng hôn.",
            "activity_type": "relaxation",
            "activity_subtype": "scenic_walk",
            "compatible_location_tags": ["culture", "urban", "food", "relax", "beach", "heritage"],
            "intensity_range": [0.1, 0.25],
            "physical_level_range": [0.1, 0.25],
            "social_level_range": [0.3, 0.7],
            "duration_range": [60, 120],
            "price_level_range": [1.0, 1.5],
            "indoor_outdoor": "outdoor",
            "weather_dependent": False,
            "time_of_day_suitable": "night",
            "sightseeing_priority": 0.55,
        },
        {
            "name_template": "Nghỉ dưỡng resort {location}",
            "description_template": "Tận hưởng kỳ nghỉ sang trọng tại resort cao cấp của {location} với hồ bơi, bãi biển riêng và dịch vụ 5 sao. Quên đi mọi lo toan trong không gian đẳng cấp.",
            "activity_type": "relaxation",
            "activity_subtype": "beach_relaxation",
            "compatible_location_tags": ["resort", "beach", "sea", "relax", "island", "entertainment"],
            "intensity_range": [0.0, 0.15],
            "physical_level_range": [0.0, 0.15],
            "social_level_range": [0.2, 0.5],
            "duration_range": [240, 480],
            "price_level_range": [3.5, 5.0],
            "indoor_outdoor": "mixed",
            "weather_dependent": False,
            "time_of_day_suitable": "anytime",
            "sightseeing_priority": 0.20,
        },
    ],

    # ── CULTURE (sightseeing_priority trung bình: 0.20-0.70) ──────────────
    "culture": [
        {
            "name_template": "Tham quan đền chùa cổ tại {location}",
            "description_template": "Khám phá kiến trúc cổ kính và tâm linh sâu sắc tại những ngôi đền, chùa linh thiêng nhất {location}. Hiểu thêm về lịch sử và văn hóa địa phương qua từng viên gạch.",
            "activity_type": "culture",
            "activity_subtype": "temple_visit",
            "compatible_location_tags": ["culture", "history", "heritage", "architecture", "temple", "spiritual"],
            "intensity_range": [0.1, 0.3],
            "physical_level_range": [0.1, 0.3],
            "social_level_range": [0.2, 0.5],
            "duration_range": [60, 180],
            "price_level_range": [1.0, 2.0],
            "indoor_outdoor": "mixed",
            "weather_dependent": False,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.65,
        },
        {
            "name_template": "Khám phá phố cổ {location}",
            "description_template": "Đắm chìm trong không khí cổ kính của phố cổ {location} với những con đường nhỏ lát đá và các cửa hiệu thủ công mỹ nghệ truyền thống. Mỗi góc phố là một câu chuyện lịch sử.",
            "activity_type": "culture",
            "activity_subtype": "heritage_walk",
            "compatible_location_tags": ["culture", "history", "heritage", "photography", "architecture"],
            "intensity_range": [0.1, 0.3],
            "physical_level_range": [0.1, 0.3],
            "social_level_range": [0.3, 0.6],
            "duration_range": [90, 240],
            "price_level_range": [1.0, 2.5],
            "indoor_outdoor": "outdoor",
            "weather_dependent": False,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.70,
        },
        {
            "name_template": "Tham quan bảo tàng lịch sử {location}",
            "description_template": "Tìm hiểu chiều sâu lịch sử và văn hóa {location} qua các hiện vật và triển lãm tại bảo tàng. Mở rộng kiến thức và hiểu thêm về vùng đất đang khám phá.",
            "activity_type": "culture",
            "activity_subtype": "museum_visit",
            "compatible_location_tags": ["culture", "history", "heritage", "education", "architecture"],
            "intensity_range": [0.0, 0.2],
            "physical_level_range": [0.0, 0.2],
            "social_level_range": [0.2, 0.5],
            "duration_range": [60, 150],
            "price_level_range": [1.0, 2.0],
            "indoor_outdoor": "indoor",
            "weather_dependent": False,
            "time_of_day_suitable": "anytime",
            "sightseeing_priority": 0.50,
        },
        {
            "name_template": "Học nấu ăn đặc sản {location}",
            "description_template": "Học làm các món ăn đặc trưng của {location} cùng đầu bếp địa phương. Tự tay chế biến và thưởng thức thành quả — trải nghiệm văn hóa ẩm thực sâu sắc nhất.",
            "activity_type": "culture",
            "activity_subtype": "cooking_class",
            "compatible_location_tags": ["culture", "food", "education", "tradition", "heritage"],
            "intensity_range": [0.2, 0.4],
            "physical_level_range": [0.1, 0.3],
            "social_level_range": [0.5, 0.9],
            "duration_range": [120, 240],
            "price_level_range": [3.0, 4.5],
            "indoor_outdoor": "indoor",
            "weather_dependent": False,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.20,
        },
        {
            "name_template": "Gặp gỡ người dân bản địa {location}",
            "description_template": "Tham quan bản làng và giao lưu với người dân địa phương tại {location}. Tìm hiểu phong tục tập quán, nghề truyền thống và cuộc sống thường ngày của họ.",
            "activity_type": "culture",
            "activity_subtype": "village_visit",
            "compatible_location_tags": ["culture", "ethnic", "village", "tradition", "mountain", "heritage"],
            "intensity_range": [0.1, 0.3],
            "physical_level_range": [0.1, 0.3],
            "social_level_range": [0.6, 1.0],
            "duration_range": [90, 180],
            "price_level_range": [1.0, 2.5],
            "indoor_outdoor": "mixed",
            "weather_dependent": False,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.55,
        },
        {
            "name_template": "Xem biểu diễn nghệ thuật truyền thống {location}",
            "description_template": "Thưởng thức các tiết mục nghệ thuật truyền thống đặc sắc của {location}: âm nhạc dân gian, múa cổ truyền và các hình thức biểu diễn độc đáo của địa phương.",
            "activity_type": "culture",
            "activity_subtype": "cultural_performance",
            "compatible_location_tags": ["culture", "history", "heritage", "music", "art", "tradition"],
            "intensity_range": [0.0, 0.1],
            "physical_level_range": [0.0, 0.1],
            "social_level_range": [0.4, 0.8],
            "duration_range": [60, 120],
            "price_level_range": [1.5, 3.0],
            "indoor_outdoor": "mixed",
            "weather_dependent": False,
            "time_of_day_suitable": "night",
            "sightseeing_priority": 0.45,
        },
    ],

    # ── FOOD (sightseeing_priority thấp: 0.10-0.25) ───────────────────────
    "food": [
        {
            "name_template": "Khám phá ẩm thực đường phố {location}",
            "description_template": "Dạo quanh các con phố để thưởng thức những món ăn đường phố ngon nổi tiếng của {location}. Từ gánh hàng rong đến quán nhỏ ven đường, mỗi góc phố là một hương vị riêng.",
            "activity_type": "food",
            "activity_subtype": "street_food_tour",
            "compatible_location_tags": ["food", "culture", "urban", "market", "tradition", "heritage"],
            "intensity_range": [0.1, 0.3],
            "physical_level_range": [0.1, 0.3],
            "social_level_range": [0.3, 0.7],
            "duration_range": [90, 180],
            "price_level_range": [1.0, 2.0],
            "indoor_outdoor": "outdoor",
            "weather_dependent": False,
            "time_of_day_suitable": "anytime",
            "sightseeing_priority": 0.15,
        },
        {
            "name_template": "Thưởng thức hải sản tươi sống {location}",
            "description_template": "Thưởng thức hải sản tươi ngon nhất của {location} tại các nhà hàng ven biển. Tôm hùm, cua, ốc, cá được chế biến đặc trưng theo phong cách địa phương.",
            "activity_type": "food",
            "activity_subtype": "seafood_dining",
            "compatible_location_tags": ["sea", "beach", "food", "seafood", "island"],
            "intensity_range": [0.0, 0.2],
            "physical_level_range": [0.0, 0.1],
            "social_level_range": [0.4, 0.8],
            "duration_range": [90, 150],
            "price_level_range": [3.0, 5.0],
            "indoor_outdoor": "mixed",
            "weather_dependent": False,
            "time_of_day_suitable": "afternoon",
            "sightseeing_priority": 0.10,
        },
        {
            "name_template": "Thử món đặc sản địa phương {location}",
            "description_template": "Khám phá kho tàng ẩm thực phong phú của {location} qua các món đặc sản chỉ có tại đây. Những hương vị độc đáo sẽ để lại ấn tượng khó quên trong chuyến đi.",
            "activity_type": "food",
            "activity_subtype": "local_cuisine",
            "compatible_location_tags": ["food", "culture", "tradition", "heritage", "ethnic"],
            "intensity_range": [0.0, 0.2],
            "physical_level_range": [0.0, 0.1],
            "social_level_range": [0.3, 0.7],
            "duration_range": [60, 120],
            "price_level_range": [1.0, 3.0],
            "indoor_outdoor": "mixed",
            "weather_dependent": False,
            "time_of_day_suitable": "anytime",
            "sightseeing_priority": 0.10,
        },
        {
            "name_template": "Tham quan chợ địa phương {location}",
            "description_template": "Khám phá chợ địa phương sôi động của {location}, nơi người dân bày bán đủ loại nông sản, gia vị và đặc sản vùng. Trải nghiệm văn hóa chợ búa truyền thống.",
            "activity_type": "food",
            "activity_subtype": "market_visit",
            "compatible_location_tags": ["food", "culture", "market", "tradition", "ethnic", "village"],
            "intensity_range": [0.1, 0.3],
            "physical_level_range": [0.1, 0.3],
            "social_level_range": [0.3, 0.7],
            "duration_range": [60, 120],
            "price_level_range": [1.0, 2.0],
            "indoor_outdoor": "mixed",
            "weather_dependent": False,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.20,
        },
        {
            "name_template": "Trải nghiệm nhà hàng đặc sắc {location}",
            "description_template": "Thưởng thức bữa ăn tại nhà hàng nổi tiếng của {location} với không gian thiết kế đẹp và menu phong phú kết hợp hương vị địa phương và hiện đại.",
            "activity_type": "food",
            "activity_subtype": "restaurant_dining",
            "compatible_location_tags": ["food", "culture", "relax", "heritage", "beach", "urban"],
            "intensity_range": [0.0, 0.1],
            "physical_level_range": [0.0, 0.1],
            "social_level_range": [0.4, 0.8],
            "duration_range": [60, 120],
            "price_level_range": [2.5, 5.0],
            "indoor_outdoor": "indoor",
            "weather_dependent": False,
            "time_of_day_suitable": "afternoon",
            "sightseeing_priority": 0.10,
        },
    ],

    # ── NIGHTLIFE (sightseeing_priority thấp: 0.10-0.40) ──────────────────
    "nightlife": [
        {
            "name_template": "Trải nghiệm bar đêm {location}",
            "description_template": "Trải nghiệm cuộc sống về đêm sôi động của {location} tại các bar và pub nổi tiếng. Âm nhạc sống động, cocktail thơm ngon và không khí cuồng nhiệt.",
            "activity_type": "nightlife",
            "activity_subtype": "bar_pub",
            "compatible_location_tags": ["nightlife", "entertainment", "urban", "beach", "sea", "fun"],
            "intensity_range": [0.3, 0.6],
            "physical_level_range": [0.1, 0.3],
            "social_level_range": [0.6, 1.0],
            "duration_range": [120, 300],
            "price_level_range": [2.5, 4.5],
            "indoor_outdoor": "indoor",
            "weather_dependent": False,
            "time_of_day_suitable": "night",
            "sightseeing_priority": 0.10,
        },
        {
            "name_template": "Ngắm thành phố về đêm {location}",
            "description_template": "Leo lên điểm cao nhất ngắm nhìn {location} lấp lánh ánh đèn về đêm. Vẻ đẹp lung linh của thành phố về đêm là trải nghiệm không thể bỏ qua khi đến đây.",
            "activity_type": "nightlife",
            "activity_subtype": "city_lights_view",
            "compatible_location_tags": ["urban", "photography", "culture", "scenic", "mountain", "beach"],
            "intensity_range": [0.1, 0.3],
            "physical_level_range": [0.1, 0.3],
            "social_level_range": [0.3, 0.7],
            "duration_range": [60, 120],
            "price_level_range": [1.0, 2.5],
            "indoor_outdoor": "outdoor",
            "weather_dependent": False,
            "time_of_day_suitable": "night",
            "sightseeing_priority": 0.40,
        },
        {
            "name_template": "Tham quan chợ đêm {location}",
            "description_template": "Dạo quanh chợ đêm sầm uất của {location} để mua sắm, thưởng thức đồ ăn vặt và tận hưởng không khí đêm đặc trưng. Nhiều món ăn ngon và quà lưu niệm hấp dẫn.",
            "activity_type": "nightlife",
            "activity_subtype": "night_market",
            "compatible_location_tags": ["food", "shopping", "culture", "nightlife", "entertainment", "urban"],
            "intensity_range": [0.1, 0.3],
            "physical_level_range": [0.1, 0.3],
            "social_level_range": [0.4, 0.8],
            "duration_range": [90, 180],
            "price_level_range": [1.0, 2.5],
            "indoor_outdoor": "outdoor",
            "weather_dependent": False,
            "time_of_day_suitable": "night",
            "sightseeing_priority": 0.20,
        },
        {
            "name_template": "Show âm nhạc biểu diễn đêm {location}",
            "description_template": "Tận hưởng đêm nhạc sống tại các tụ điểm văn nghệ của {location}. Tiết mục đặc sắc kết hợp giữa âm nhạc truyền thống và hiện đại trong không gian ấm cúng.",
            "activity_type": "nightlife",
            "activity_subtype": "live_music",
            "compatible_location_tags": ["entertainment", "music", "culture", "nightlife", "urban"],
            "intensity_range": [0.1, 0.4],
            "physical_level_range": [0.0, 0.2],
            "social_level_range": [0.5, 0.9],
            "duration_range": [90, 180],
            "price_level_range": [2.0, 4.0],
            "indoor_outdoor": "indoor",
            "weather_dependent": False,
            "time_of_day_suitable": "night",
            "sightseeing_priority": 0.15,
        },
    ],

    # ── SHOPPING (sightseeing_priority rất thấp: 0.05-0.25) ───────────────
    "shopping": [
        {
            "name_template": "Mua đồ lưu niệm thủ công {location}",
            "description_template": "Chọn lựa những món quà lưu niệm thủ công mang đặc trưng {location} tại các cửa hàng và chợ địa phương. Mỗi món đồ là một tác phẩm nghệ thuật độc đáo.",
            "activity_type": "shopping",
            "activity_subtype": "souvenir_shopping",
            "compatible_location_tags": ["culture", "shopping", "craft", "art", "tradition", "heritage"],
            "intensity_range": [0.0, 0.2],
            "physical_level_range": [0.0, 0.2],
            "social_level_range": [0.2, 0.6],
            "duration_range": [60, 120],
            "price_level_range": [1.5, 3.5],
            "indoor_outdoor": "mixed",
            "weather_dependent": False,
            "time_of_day_suitable": "anytime",
            "sightseeing_priority": 0.10,
        },
        {
            "name_template": "Mua đặc sản địa phương {location}",
            "description_template": "Tìm mua những đặc sản nổi tiếng của {location} để làm quà hoặc thưởng thức. Từ thực phẩm chế biến, gia vị đến đồ uống đặc trưng của vùng.",
            "activity_type": "shopping",
            "activity_subtype": "local_products",
            "compatible_location_tags": ["food", "culture", "tradition", "market", "ethnic"],
            "intensity_range": [0.0, 0.2],
            "physical_level_range": [0.0, 0.2],
            "social_level_range": [0.2, 0.5],
            "duration_range": [60, 120],
            "price_level_range": [1.0, 3.0],
            "indoor_outdoor": "mixed",
            "weather_dependent": False,
            "time_of_day_suitable": "anytime",
            "sightseeing_priority": 0.10,
        },
        {
            "name_template": "Khám phá làng nghề thủ công {location}",
            "description_template": "Thăm các làng nghề truyền thống tại {location} để xem thợ thủ công làm việc và mua trực tiếp sản phẩm chất lượng. Hiểu hơn về nghề thủ công bản địa.",
            "activity_type": "shopping",
            "activity_subtype": "craft_village",
            "compatible_location_tags": ["culture", "craft", "art", "tradition", "heritage", "village", "ethnic"],
            "intensity_range": [0.1, 0.3],
            "physical_level_range": [0.1, 0.3],
            "social_level_range": [0.3, 0.6],
            "duration_range": [90, 180],
            "price_level_range": [1.0, 3.0],
            "indoor_outdoor": "mixed",
            "weather_dependent": False,
            "time_of_day_suitable": "morning",
            "sightseeing_priority": 0.25,
        },
        {
            "name_template": "Shopping trung tâm thương mại {location}",
            "description_template": "Tham quan và mua sắm tại trung tâm thương mại hiện đại nhất {location}. Nhiều thương hiệu quốc tế và địa phương, khu ẩm thực và giải trí đa dạng.",
            "activity_type": "shopping",
            "activity_subtype": "mall_shopping",
            "compatible_location_tags": ["shopping", "entertainment", "urban", "food", "fun"],
            "intensity_range": [0.0, 0.2],
            "physical_level_range": [0.0, 0.2],
            "social_level_range": [0.3, 0.7],
            "duration_range": [120, 240],
            "price_level_range": [2.0, 5.0],
            "indoor_outdoor": "indoor",
            "weather_dependent": False,
            "time_of_day_suitable": "afternoon",
            "sightseeing_priority": 0.05,
        },
    ],
}

